### ISSUE TITLE
Add mount option for pitot tube into wings

### ISSUE THREAD

**Issue by nhadrian** [StephenCarlson/MiniHawk-VTOL#20]
Measuring airspeed is really useful (mandatory) if you'd like to tune plane perfectly for auto missions.

**Comment by StephenCarlson** [comment]
Solved in ede11e9. The wings have the shaft for the tube defined, assuming 4mm diameter and some allowance for the bend static-port nipple when inserting the assembly. The tube is angled 3 degrees down to correspond to the lower side of the airspeed range. The winglet GPS pocket removal includes a space for the pitot pressure sensor; the pressure sense lines are routed from the pitot probe pocket in the wing to the pressure sensor at the winglet.
