### ISSUE TITLE
Add mount possibility for RF modules and antennas into the wing, near the wing-tip

### ISSUE THREAD

**Issue by nhadrian** [StephenCarlson/MiniHawk-VTOL#21]
Placing vTx or telemetry and antenna far from other electronics would improve flight range and video quality.

**Comment by StephenCarlson** [comment]
Near duplicate of #6 , but with added detail about antenna placement. Agree that antennas should be at wingtips. Also related: #19

**Comment by StephenCarlson** [comment]
Solved by ede11e9, also see #6 , pretty much the same thing.
