### ISSUE TITLE
Paper available?

### ISSUE THREAD

**Issue by github-throwaway** [StephenCarlson/MiniHawk-VTOL#41]
Hi Stephen,

I'm currently writing my master's thesis about UAS in search and rescue. I think your project is fascinating. Would you be able to share your paper **[The MiniHawk-VTOL: Design, Modeling, and Experiments of a Rapidly-prototyped Tiltrotor UAV](https://ieeexplore.ieee.org/abstract/document/9476731)**?

**Comment by StephenCarlson** [comment]
Yep! Here is where I've previously posted a copy of the PDF: https://github.com/StephenCarlson/MiniHawk-VTOL/discussions/40#discussioncomment-2224433
